name: Github Context

on:
  workflow_dispatch
jobs:
  Context:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: | # instead of using run echo / run echo / run echo
          echo 'Actor ${{github.actor}}'
          echo 'Event ${{github.event_name}}'
          echo 'Reference detail ${{github.ref}}'
          echo 'sha value ${{github.sha}}'
          echo 'Run details ${{github.run_id}}'
          echo 'Runner number details ${{github.run_number}}'
  
