name: Github Env Secrets Vars Matrix Context

env:
  MY_VAR: 'workflow'

on:
  workflow_dispatch
jobs:
  Context:
    env:
      MY_VAR: 'jobs'
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Print
        env:
          MY_VAR: 'steps'
        run: | # instead of using run echo / run echo / run echo
          echo 'Actor ${{github.actor}}'
          echo 'Event ${{github.event_name}}'
          echo 'Reference detail ${{github.ref}}'
          echo 'sha value ${{github.sha}}'
          echo 'Run details ${{github.run_id}}'
          echo 'Runner number details ${{github.run_number}}'
          echo 'Env value is ${{env.MY_VAR}}'
          echo 'Global env value is ${{vars.MY_VAR}}'
          echo 'Secret 'username' is ${{secrets.USERNAME}}'
