# Name of the workflow
name: First Workflow

run-name: DEBUG| ${{inputs.debug}}

# Trigger
on: 
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  build: # job name
    runs-on: ubuntu-latest # github hosted runner
    steps:
     - name: Echo
       run: echo "Welcome to first workflow - Ubuntu"
     - name: Exit
       run: exit 1
  deploy: # second job
    needs: build
    runs-on: windows-latest
    steps:
     - name: Echo
       run: echo "Welcome to second workflow - Windows"
    
