name: Setup node
on:
  workflow_dispatch

jobs:
  setup-node:
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 23, 26]
    runs-on: ubuntu-latest
    steps:
       - name: Setup Node.js environment
         uses: actions/setup-node@v3.9.1
         with:
           node-version: ${{matrix.node-version}}
